### model
model_name_or_path: models-hf/CodeLlama-7b-hf

### method
stage: sft
do_train: true
finetuning_type: lora
# lora_rank: 64
# lora_target: all
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: original-pie
# mix_strategy: concat
template: code_opt-codellama
cutoff_len: 3072
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: code_edit_results/original-pie/codellama-7b/lora_8/
logging_steps: 1
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard
logging_dir:  code_edit_results/original-pie/codellama-7b/lora_8/logs/
print_param_status: false
save_strategy: epoch

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0
per_device_eval_batch_size: 1
eval_strategy: "no"